{{- range $group := .Values.groups }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-token" $group.name | quote }}
  namespace: {{ if eq $group.scope "cluster" }}"kube-system"{{ else }}{{ $group.namespace | quote }}{{ end }}
  annotations:
    kubernetes.io/service-account.name: {{ $group.name | quote }}
  labels:
    {{- include "kubeconfig-factory.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "token-secret"
    kubeconfig-factory/group: {{ $group.name | quote }}
    kubeconfig-factory/scope: {{ $group.scope | quote }}
    kubeconfig-factory/role: {{ $group.role | quote }}
type: kubernetes.io/service-account-token
{{- end }}
